name: just
description: A flutter package for fstar.
version: 2.0.0
homepage: https://github.com/mikai233/just
publish_to: "none"
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  html: ^0.15.0
  gbk2utf8:
    git: https://github.com/mikai233/gbk2utf8.git
#  path: ^1.7.0

dev_dependencies:
  pedantic:
    git: https://github.com/google/pedantic.git
  test: ^1.17.10
